name: Zip Files

on: [push]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: scrabble.py
          dest: ScrabblePython.zip
      - uses: actions/upload-artifact@v2
        with:
          name: ScrabblePython.zip
          path: ${{ github.workspace }}/ScrabblePython.zip
